#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

. /lib/functions.sh

logger "$BUTTON pressed for $SEEN seconds"

if [ "$SEEN" -gt 2 ]
then
	echo "FACTORY RESET" > /dev/console
	jffs2reset -y && reboot &
fi
